/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RateSessionRouteImport } from './routes/rate-session'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicNotifyBookingRouteImport } from './routes/api/public/notify-booking'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RateSessionRoute = RateSessionRouteImport.update({
  id: '/rate-session',
  path: '/rate-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicNotifyBookingRoute = ApiPublicNotifyBookingRouteImport.update({
  id: '/api/public/notify-booking',
  path: '/api/public/notify-booking',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rate-session': typeof RateSessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/notify-booking': typeof ApiPublicNotifyBookingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/rate-session': typeof RateSessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/api/public/notify-booking': typeof ApiPublicNotifyBookingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/rate-session': typeof RateSessionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/api/public/notify-booking': typeof ApiPublicNotifyBookingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/rate-session'
    | '/sitemap.xml'
    | '/thank-you'
    | '/admin'
    | '/api/public/notify-booking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/rate-session'
    | '/sitemap.xml'
    | '/thank-you'
    | '/admin'
    | '/api/public/notify-booking'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/rate-session'
    | '/sitemap.xml'
    | '/thank-you'
    | '/_authenticated/admin'
    | '/api/public/notify-booking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RateSessionRoute: typeof RateSessionRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiPublicNotifyBookingRoute: typeof ApiPublicNotifyBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-session': {
      id: '/rate-session'
      path: '/rate-session'
      fullPath: '/rate-session'
      preLoaderRoute: typeof RateSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notify-booking': {
      id: '/api/public/notify-booking'
      path: '/api/public/notify-booking'
      fullPath: '/api/public/notify-booking'
      preLoaderRoute: typeof ApiPublicNotifyBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RateSessionRoute: RateSessionRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRoute,
  ApiPublicNotifyBookingRoute: ApiPublicNotifyBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
